### ISSUE TITLE
"getting started" setup fails

### ISSUE THREAD

**Issue by bghmarmalade** [dennisreimann/uiengine#32]
**Describe the bug**
I cannot start the demo as described in https://uiengine.uix.space/basics/getting-started/

**To Reproduce**
follow steps from https://uiengine.uix.space/basics/getting-started/
the step
npx uiengine build --serve --watch
fails.

**Expected behavior**
a basic UIengine demo project running.

**Screenshots**

**Additional context**
node -v
v8.15.0
npm -v
6.4.1

console output:
/uiengine-demo$ npx uiengine build --serve --watch
🚨  Build failed!

TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports (/home/boris/spoco-mce/uiengine-demo/node_modules/dir-glob/index.js:44:25)
    at globDirs (/home/boris/spoco-mce/uiengine-demo/node_modules/globby/index.js:58:9)
    at getPattern (/home/boris/spoco-mce/uiengine-demo/node_modules/globby/index.js:61:64)
    at Promise.all.globTasks.map.task (/home/boris/spoco-mce/uiengine-demo/node_modules/globby/index.js:72:69)
    at Array.map (<anonymous>)
    at module.exports (/home/boris/spoco-mce/uiengine-demo/node_modules/globby/index.js:72:41)
    at findPageIds (/home/boris/spoco-mce/uiengine-demo/node_modules/@uiengine/core/src/page.js:57:27)
    at Object.fetchAll (/home/boris/spoco-mce/uiengine-demo/node_modules/@uiengine/core/src/page.js:67:25)
    at Object.generate (/home/boris/spoco-mce/uiengine-demo/node_modules/@uiengine/core/src/core.js:68:29)
    at <anonymous>

**Comment by dennisreimann** [comment]
Thanks, I had to dig a bit, but it seems to be related to a recent change in a dependencies dependency, which has been published yesterday: kevva/dir-glob#12

For now I'd rather fix this by adding `"dir-glob": "2.0.0"` to the `devDependencies`, as I hope they fix the issue on their end.

Does this work for you?

**Comment by dennisreimann** [comment]
Just saw that this has been already fixed in our dependency already: sindresorhus/globby#99

I'll try to publish an updated UIengine version this weekend, for now you can circumvent the issue as described above. 

Thanks for reporting!

**Comment by dennisreimann** [comment]
I published the `2.0.0-beta.0` which should fix the issue.

**Comment by bghmarmalade** [comment]
Working now, thanks.
